### ISSUE TITLE
Desenvolvimento do webscraping - LinkedIn

### ISSUE THREAD

**Issue by renata-olivmachado** [SouJunior/dashboard-midias#16]
**Desenvolver webscraping Python, podendo usar selenium ou outra lib.
O webscraping deve logar no LinkedIn, acessar a página do SJ e extrair os dados para o AWS S3.**

**Sub-tasks:**

- [ ]  Logar no LinkedIn - 1
- [ ]  Acessar análises da página oficial do SJ - 1
- [ ]  Editar filtro - 1
- [ ]  Download do arquivo apontando para o AWS S3 - 2
- [ ]  Loop pelas abas - 2****

**Comment by renata-olivmachado** [comment]
```[tasklist]
### logar no linkedin
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft task
```
